version: "3.8"
services:
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_DB=${DB_DATABASE:-database}
      - POSTGRES_USER=${DB_USERNAME:-username}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-password}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app.local
  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - fpm
    volumes:
      - ./public:/var/www/html/public
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/ssl:/etc/nginx/ssl
      - ./docker/volumes/var/run/php:/var/run/php
    networks:
      app.local:
        aliases:
          - project
  fpm:
    image: app/fpm
    build:
      context: ./
      target: build_dev
      dockerfile: docker/fpm/Dockerfile
    container_name: fpm
    depends_on:
      - db
    volumes:
      - ./:/var/www/html
#      - /etc/ssl/certs:/etc/ssl/certs:ro
      - ./docker/volumes/.bash_history:/home/symfony-quick-starter/.bash_history
      - ./docker/volumes/var/run/php:/var/run/php
    networks:
      - app.local


volumes:
  postgres-data: ~

networks:
  app.local:
    name: app.local
    external: true
